/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Core.GUI;

import Abstracts.Logic.BridgingEvent;
import Abstracts.Logic.EncounterEvent;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.UIManager;

/**
 *
 * @author DXG11
 */
public class EventGui extends javax.swing.JPanel {

    /**
     * Creates new form Event
     */
    private GuiMan man;
    private EncounterEvent encounter;

    public EventGui(GuiMan man) {
        this.man = man;
        initComponents();
    }

    public void setNextEncounter(EncounterEvent encounter) {
        this.encounter = encounter;
        man.setCurrentEncounter(encounter);
        this.eventText.setText(encounter.getDescription());
        buttonSetup(option1Button, encounter.OptionOne);
        buttonSetup(option2Button, encounter.OptionTwo);
        buttonSetup(option3Button, encounter.OptionThree);
        buttonSetup(option4Button, encounter.OptionFour);

    }

    private void buttonSetup(JButton button, BridgingEvent option) {
        
        if (option != null) {
            button.setVisible(true);
            if (option.condition) {
                button.setText("<html>"+option.optionDescription+"</html>");
                button.setEnabled(true);
            } else {
                button.setText("<html>"+option.conditionRequirement+"</html>");
                button.setEnabled(false);
            }
        } else {
            button.setText("");
            button.setEnabled(false);
            button.setVisible(false);
        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveButton = new javax.swing.JButton();
        option1Button = new javax.swing.JButton();
        option2Button = new javax.swing.JButton();
        option3Button = new javax.swing.JButton();
        option4Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventText = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(600, 600));

        saveButton.setText("Save");
        saveButton.setName("Save"); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        option1Button.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        option1Button.setForeground(new java.awt.Color(0, 0, 0));
        option1Button.setText("jButton2");
        option1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option1ButtonActionPerformed(evt);
            }
        });

        option2Button.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        option2Button.setForeground(new java.awt.Color(0, 0, 0));
        option2Button.setText("jButton3");
        option2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option2ButtonActionPerformed(evt);
            }
        });

        option3Button.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        option3Button.setForeground(new java.awt.Color(0, 0, 0));
        option3Button.setText("jButton4");
        option3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option3ButtonActionPerformed(evt);
            }
        });

        option4Button.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        option4Button.setForeground(new java.awt.Color(0, 0, 0));
        option4Button.setText("jButton5");
        option4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option4ButtonActionPerformed(evt);
            }
        });

        eventText.setEditable(false);
        eventText.setColumns(20);
        eventText.setLineWrap(true);
        eventText.setRows(5);
        eventText.setWrapStyleWord(true);
        jScrollPane1.setViewportView(eventText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(saveButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(option1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(option2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(option3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(option4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(option1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void option1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1ButtonActionPerformed
        // TODO add your handling code here:
        man.gotToOutCome(encounter.OptionOne);
    }//GEN-LAST:event_option1ButtonActionPerformed

    private void option2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2ButtonActionPerformed
        // TODO add your handling code here:
        man.gotToOutCome(encounter.OptionTwo);
    }//GEN-LAST:event_option2ButtonActionPerformed

    private void option3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option3ButtonActionPerformed
        // TODO add your handling code here:
        man.gotToOutCome(encounter.OptionThree);
    }//GEN-LAST:event_option3ButtonActionPerformed

    private void option4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option4ButtonActionPerformed
        // TODO add your handling code here:
        man.gotToOutCome(encounter.OptionFour);
    }//GEN-LAST:event_option4ButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        man.save();
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea eventText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton option1Button;
    private javax.swing.JButton option2Button;
    private javax.swing.JButton option3Button;
    private javax.swing.JButton option4Button;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
